### ISSUE TITLE
Issue with encoding type

### ISSUE THREAD

**Issue by vasner** [jeroen/webutils#2]
I have an issue with sending 'multipart/form-data' and setting charset=utf-8.

Issue came from:
https://github.com/opencpu/opencpu/issues/292

> Works well:
> curl 'http://cloud.opencpu.org/ocpu/library/utils/R/read.csv' -H 'Content-Type: multipart/form-data; boundary=1520959971324' --data-binary $'--1520959971324\r\nContent-Disposition: form-data; name="file"; filename="dataset.csv"\r\nContent-Type: application/octet-stream\r\n\r\ndiesel,turbo\n0,0\r\n\r\n--1520959971324\r\nContent-Disposition: form-data; name="blank.lines.skip"\r\n\r\nFALSE\r\n--1520959971324--\r\n'
> 
> Failed:
> curl 'http://cloud.opencpu.org/ocpu/library/utils/R/read.csv' -H 'Content-Type: multipart/form-data; boundary=1520959971324; charset=utf-8' --data-binary $'--1520959971324\r\nContent-Disposition: form-data; name="file"; filename="dataset.csv"\r\nContent-Type: application/octet-stream\r\n\r\ndiesel,turbo\n0,0\r\n\r\n--1520959971324\r\nContent-Disposition: form-data; name="blank.lines.skip"\r\n\r\nFALSE\r\n--1520959971324--\r\n'
> 
> With charset=utf-8 version 1.6.6 worked well, but 2.0.5 does not.
> 
> What is default charset in OpenCPU 2.0.5?
> Why OpenCPU 2.0.5 does not work with "charset=utf-8" parameter in header?

**Comment by jeroen** [comment]
Fixed via https://github.com/jeroen/webutils/commit/58abf870567e24bed0e41f507a7edcb35b7d24c4

**Comment by vasner** [comment]
Thank you!
