### ISSUE TITLE
Quoted multipart boundary

### ISSUE THREAD

**Issue by meztez** [jeroen/webutils#6]
https://github.com/jeroen/webutils/blob/835953ea30de789293082f7f4c1c0f45566fae21/R/get_boundary.R#L9

Per [RFC2046](https://www.ietf.org/rfc/rfc2046.txt)

> WARNING TO IMPLEMENTORS:  The grammar for parameters on the Content-
>    type field is such that it is often necessary to enclose the boundary
>    parameter values in quotes on the Content-type line.  This is not
>    always necessary, but never hurts. Implementors should be sure to
>    study the grammar carefully in order to avoid producing invalid
>    Content-type fields.  Thus, a typical "multipart" Content-Type header
>    field might look like this:
> 
>      Content-Type: multipart/mixed; boundary=gc0p4Jq0M2Yt08j34c0p
> 
>    But the following is not valid:
> 
>      Content-Type: multipart/mixed; boundary=gc0pJq0M:08jU534c0p
> 
>    (because of the colon) and must instead be represented as
> 
>      Content-Type: multipart/mixed; boundary="gc0pJq0M:08jU534c0p"
> 
>    This Content-Type value indicates that the content consists of one or
>    more parts, each with a structure that is syntactically identical to
>    an RFC 822 message, except that the header area is allowed to be
>    completely empty, and that the parts are each preceded by the line

ref https://github.com/rstudio/plumber/pull/924

**Comment by jeroen** [comment]
Do you want to send a PR?
